### ISSUE TITLE
No module named "InviwoMeanFreePathCLModule".

### ISSUE THREAD

**Issue by ChuckDanglars** [ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data#1]
Hello, Daniel
I am implement your code and it come up with some errors. I have worked on it for a couple days but still cannot solves it. 
In the Inviwo, there is no module named "InviwoMeanFreePathCLModule".
Could you please help me with it? Thanks a lot.
----------------------------------------------------
CMake Error at /home/chuck/Documents/inviwo-0.9.7/cmake/globalmacros.cmake:832 (find_package):
  By not providing "FindInviwoMeanFreePathCLModule.cmake" in
  CMAKE_MODULE_PATH this project has asked CMake to find a package
  configuration file provided by "InviwoMeanFreePathCLModule", but CMake did
  not find one.

  Could not find a package configuration file provided by
  "InviwoMeanFreePathCLModule" with any of the following names:

    InviwoMeanFreePathCLModuleConfig.cmake
    inviwomeanfreepathclmodule-config.cmake
------------------------

**Comment by ResearchDaniel** [comment]
The module is not used but still seem to remain in modules/progressivephotonmapping/depends.cmake
Does removing the line with "InviwoMeanFreePathCLModule" in the depends.cmake resovle the issue?

**Comment by ChuckDanglars** [comment]
I have removing the line with "InviwoMeanFreePathCLModule". And a new error comes in  modules\uniformgridcl\uniformgrid3dreader.cpp(57): error C2653: “filesystem”: is not a class or namespace name.
It seems to be the boost error but I cannot fix it.
I am using windows10, vs 2015.
![image](https://user-images.githubusercontent.com/6948676/30168968-9095d910-941d-11e7-86cd-71f1420c7728.png)
The Boost_DIR can never be setted whaterver it is.  I'm really confused with this.
Do you think it is the Boost library's error? Or something else?
Any advice is great appreciation for me?
Thanks a lot.

**Comment by ChuckDanglars** [comment]
Hi, Daniel.
I have fix the prvious errors that there seems to miss some header files. So I added them as where it is needed.
But, when I am running the software, that is some errors like this:
-----------
(BufferCLGL) [e:\inviwo-0.9.7\modules\opencl\buffer\bufferclgl.cpp, 123]: Error:clEnqueueReadBuffer(-5), CL_OUT_OF_RESOURCES 

(LightSampleMeshIntersectionCL) [e:\inviwo\otherrepo\modules\lightcl\lightsamplemeshintersectioncl.cpp, 85]: Error:clEnqueueReadBuffer(-5), CL_OUT_OF_RESOURCES 

(OpenCL) [e:\inviwo-0.9.7\modules\opencl\inviwoopencl.cpp, 168]: E:/Inviwo/otherrepo/modules/rndgenmwc64x/cl/randstategen.cl build error:


(KernelManager) [e:\inviwo-0.9.7\modules\opencl\kernelmanager.cpp, 110]: Failed to find kernel:MWC64X_GenerateRandomState

(PhotonTracerCL) [e:\inviwo\otherrepo\modules\progressivephotonmapping\photontracercl.cpp, 127]: Error:clEnqueueWriteBuffer(-5), CL_OUT_OF_RESOURCES 

(PhotonTracerCL) [e:\inviwo\otherrepo\modules\progressivephotonmapping\photontracercl.cpp, 127]: Error:clEnqueueWriteBuffer(-5), CL_OUT_OF_RESOURCES 

(ProcessorNetworkEvaluator) [e:\inviwo-0.9.7\src\core\network\processornetworkevaluator.cpp, 133]: clEnqueueFillBuffer
(PhotonTracerCL) [e:\inviwo\otherrepo\modules\progressivephotonmapping\photontracercl.cpp, 127]: Error:clEnqueueWriteBuffer(-5), CL_OUT_OF_RESOURCES 

(PhotonTracerCL) [e:\inviwo\otherrepo\modules\progressivephotonmapping\photontracercl.cpp, 127]: Error:clEnqueueWriteBuffer(-5), CL_OUT_OF_RESOURCES 

(PhotonToLightVolumeProcessorCL) [e:\inviwo\otherrepo\modules\progressivephotonmapping\processor\photontolightvolumeprocessorcl.cpp, 421]: Error:clEnqueueWriteBuffer(-5), CL_OUT_OF_RESOURCES 

Do you have any idea of this error?
Thanks very much!
------------

**Comment by ResearchDaniel** [comment]
Looks like you are out of memory. Could be something that goes wrong before as well. What does the log info at startup say about your OpenCL device and so on?

**Comment by ChuckDanglars** [comment]
Hi，this is my startup log:
----
(InviwoInfo) Inviwo Version: 0.9.7
(InviwoInfo) Base Path: E:/inviwo-0.9.7
(InviwoInfo) Config: Visual Studio 14 2015 Win64 [Release]
(InviwoInfo) Qt Version 5.7.0
(PyInviwo) Python version: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
(SystemInfo) OS: Microsoft Windows 8 64-bit
(SystemInfo) CPU 1-24: Intel Xeon
(SystemInfo) RAM: Total - 23.92 GB, Available - 20.80 GB
(SystemInfo) Disk: C:\ Total - 100.10 GB, Free - 9.34 GB
(SystemInfo) Disk: D:\ Total - 78.12 GB, Free - 36.61 GB
(SystemInfo) Disk: E:\ Total - 703.12 GB, Free - 431.12 GB
(SystemInfo) Disk: J:\ Total - 1.82 TB, Free - 176.78 GB
(SystemInfo) Processor Memory: Resident - 89.90 MB, Shared - 16777216.00 TB, Virtual - 382.25 MB
(OpenGLInfo) GPU Vendor: NVIDIA Corporation
(OpenGLInfo) GPU Renderer: Quadro K2000/PCIe/SSE2
(OpenGLInfo) Dedicated video memory: 2.00 GB
(OpenGLInfo) OpenGL Version: 4.5.0 NVIDIA 376.51
(OpenGLInfo) OpenGL Profile: Core
(OpenGLInfo) GLSL version: 4.50 NVIDIA
(OpenCLInfo) CL_DEVICE_TYPE: GPU
(OpenCLInfo) CL_DEVICE_NAME: Quadro K2000
(OpenCLInfo) CL_DEVICE_VENDOR: NVIDIA Corporation
(OpenCLInfo) CL_DRIVER_VERSION: 376.51
(OpenCLInfo) CL_DEVICE_PROFILE: FULL_PROFILE
(OpenCLInfo) CL_DEVICE_VERSION: OpenCL 1.2 CUDA

It will load the workspace like this, and the errors occured. 
Is this workspace correct with you version?
The rendered image is as shown in the picture.
----
![image](https://user-images.githubusercontent.com/6948676/30216588-17158f4e-94e6-11e7-97f7-df00e4f1c787.png)
And when I am interactive with the canvas window, it freezed and error like this.
----
![image](https://user-images.githubusercontent.com/6948676/30216804-c13ea604-94e6-11e7-96fb-d7fb997cd129.png)
Is this because of the wrong version of opencl?
Thanks for you help!
---

**Comment by ResearchDaniel** [comment]
Sorry for late reply but I've tried to investigate what could be the cause. I have not tried it on a Quadro graphics card but it should work. The workspace looks correct, but the image should  of course not be black :)
Some things that could be worth checking:
- I've had some trouble with OpenGL synchronization when using async queues. Try replacing getAsyncQueue() with getQueue() on line 352 in photontolightvolumeprocessorcl.cpp
- Check if the quadro card is selected as Default device in OpenCL device in (Settings->OpenCL Settings) and that OpenGL sharing is enabled in the settings.
- What is the first error that you get, clEnqueuFillBuffer?
- I noted that you get an OpenCL build error when compiling modules/rndgenmwc64x/cl/randstategen.cl. Any info on what kind of error it is? There does not seem to be any output in the log.

**Comment by ChuckDanglars** [comment]
Sorry for late reply. I've tried your sugesstion.
(1) "replacing getAsyncQueue() with getQueue() on line 352 in photontolightvolumeprocessorcl.cpp" seem no work and the getQueue() make the software freezed and no output log.
(2) I have made a progress to display the rendering results. But there still some errors as shown bellow.
---
![image](https://user-images.githubusercontent.com/6948676/31331985-2ecc4ec2-ad17-11e7-8674-0ebea8f95a3a.png)


(InviwoInfo) Inviwo Version: 0.9.7
(InviwoInfo) Base Path: E:/inviwo-0.9.7
(InviwoInfo) Config: Visual Studio 14 2015 Win64 [Release]
(InviwoInfo) Qt Version 5.7.0
(PyInviwo) Python version: 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]
(SystemInfo) OS: Microsoft Windows 8 64-bit
(SystemInfo) CPU 1-24: Intel Xeon
(SystemInfo) RAM: Total - 23.92 GB, Available - 13.95 GB
(SystemInfo) Disk: C:\ Total - 100.10 GB, Free - 1.57 GB
(SystemInfo) Disk: D:\ Total - 78.12 GB, Free - 32.64 GB
(SystemInfo) Disk: E:\ Total - 703.12 GB, Free - 427.98 GB
(SystemInfo) Disk: F:\ Total - 1.82 TB, Free - 941.05 GB
(SystemInfo) Disk: G:\ Total - 298.09 GB, Free - 136.55 GB
(SystemInfo) Disk: J:\ Total - 1.82 TB, Free - 83.56 GB
(SystemInfo) Processor Memory: Resident - 91.50 MB, Shared - 16777216.00 TB, Virtual - 383.08 MB
(OpenGLInfo) GPU Vendor: NVIDIA Corporation
(OpenGLInfo) GPU Renderer: Quadro K2000/PCIe/SSE2
(OpenGLInfo) Dedicated video memory: 2.00 GB
(OpenGLInfo) OpenGL Version: 4.5.0 NVIDIA 376.51
(OpenGLInfo) OpenGL Profile: Core
(OpenGLInfo) GLSL version: 4.50 NVIDIA
(OpenCLInfo) CL_DEVICE_TYPE: GPU
(OpenCLInfo) CL_DEVICE_NAME: Quadro K2000
(OpenCLInfo) CL_DEVICE_VENDOR: NVIDIA Corporation
(OpenCLInfo) CL_DRIVER_VERSION: 376.51
(OpenCLInfo) CL_DEVICE_PROFILE: FULL_PROFILE
(OpenCLInfo) CL_DEVICE_VERSION: OpenCL 1.2 CUDA
(PVMVolumeReader) Loaded volume: E:/inviwo-0.9.7/data/volumes/Subclavia.pvm size: 24.00 MB
(ProcessorNetworkEvaluator) Processed Volume Source: 759.329ms
(VolumeMinMaxCLProcessor) [E:\Inviwo\chuckrepo\modules\uniformgridcl\processors\volumeminmaxclprocessor.cpp, 146]: Error:clEnqueueNDRangeKernel(-54), CL_INVALID_WORK_GROUP_SIZE 

(ScopedClockCL) [E:\inviwo-0.9.7\modules\opencl\clockcl.cpp, 46]: Error:clWaitForEvents(-58), CL_INVALID_EVENT 

(MinMaxUniformGrid3DImportanceCLProcessor) : 0.010688 ms
(ProgressivePhotonTracerCL) Photon tracing: 170.396 + 80.3118 = 250.708 ms
(ProgressivePhotonTracerCL) Computed photons: 2097152 = 100 %
(ProcessorNetworkEvaluator) Processed ProgressivePhotonTracer: 2s 792.86ms
(PhotonToLightVolumeProcessorCL) Exec time (clear, computation, copy): 0.007072 + 41.6248 + 0.008928 = 41.6408 ms
(ProcessorNetworkEvaluator) [E:\inviwo-0.9.7\src\core\network\processornetworkevaluator.cpp, 133]: clEnqueueCopyBuffer
(VolumeRaycasterCLProcessor) : 18.1292 ms
(CompositeProperty) [E:\inviwo-0.9.7\src\core\properties\compositeproperty.cpp, 103]: CompositeProperty mismatch. Unable to link
(CompositeProperty) [E:\inviwo-0.9.7\src\core\properties\compositeproperty.cpp, 103]: CompositeProperty mismatch. Unable to link
(VolumeRaycasterCLProcessor) : 18.1382 ms
(CompositeProperty) [E:\inviwo-0.9.7\src\core\properties\compositeproperty.cpp, 103]: CompositeProperty mismatch. Unable to link
(CompositeProperty) [E:\inviwo-0.9.7\src\core\properties\compositeproperty.cpp, 103]: CompositeProperty mismatch. Unable to link
(VolumeRaycasterCLProcessor) : 19.4173 ms

I have search for this issue that it seems to be some wrong setting of the work group size and region size in the "Min-max uniform grid" module as the default region size is 8 and the default work group size is vec3(8).  When I set it to be region size = 16 and work group size = vec3(64), it have the result and the error occurs. 
So how do you think about this issue? Is it correct to consider region size as local size as in Opencl?
There I read an example:  Let's say you have 10,000 things you want to process with your CL kernel. That's your global size: 10,000. Perhaps you want to process these in groups of 100 things. That's your local size: 100. Because 10,000/100 == 100, this particular arrangement will give you 100 workgroups. Above, you have a global size of 16, and a local size of 128. This doesn't make sense for OpenCL -- 16 / 128. Perhaps you wanted 16*128 as your global size, and 128 as your local size? That would yield 16 workgroups of 128 items each. [https://stackoverflow.com/questions/7996537/cl-invalid-work-group-size-error]
---

(3)  The setting of default device and that OpenGL sharing in the settings was all conformed.
---

(4) Now the output log is, warning occured when interacting with the rendering windows.  How do you think about this issues? 
Thanks very much for your help!
---
![image](https://user-images.githubusercontent.com/6948676/31332163-e4d8a288-ad17-11e7-94f5-ef88b02b1cbb.png)

**Comment by ResearchDaniel** [comment]
> So how do you think about this issue? Is it correct to consider region size as local size as in Opencl?

Yes, that should be fine. Work group size is just for performance.

>  Now the output log is, warning occured when interacting with the rendering windows. How do you think about this issues?

It looks like there are some errors in the linking of properties between processors. You can inspect the linking by double-clicking on the white dotted lines between processors. Try remove one link at a time to see which one of them is causing the warning (probably from VolumeRayCasterCLProcessor).

Great that you managed to get the rendering up and running!

**Comment by ChuckDanglars** [comment]
Thanks very much for you help!

**Comment by firebrain7** [comment]
how to compile this project without a root cmakelist file?
thanks!
@ChuckDanglars @ResearchDaniel
