### ISSUE TITLE
the question about the implementation

### ISSUE THREAD

**Issue by firebrain7** [ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data#5]
Hi, Daniel
Did you have made the devlopment document about the implementation of this project?

**Comment by ResearchDaniel** [comment]
Hmm, you mean other than the paper "Correlated Photon Mapping for Interactive Global Illumination of Time-Varying Volumetric Data" http://scivis.itn.liu.se/publications/2017/JY17/JonssonCorrelatedPhotonMapping.pdf

**Comment by firebrain7** [comment]
thank you, I have seen this paper. 
I mean when you are coding, have you ever made the implementation docs?

**Comment by firebrain7** [comment]
such as the relation about the class and the function

**Comment by ResearchDaniel** [comment]
Ah, unfortunately this was done more or less like a solo project so not much time was spent on documentation. You can send me an email if you have some questions about how it works.

**Comment by firebrain7** [comment]
thanks a lot! what's your email?

**Comment by ResearchDaniel** [comment]
daniel.jonsson@liu.se

**Comment by firebrain7** [comment]
thank you, i will try to understand the project before asking you. 
Have a nice day :)
