### ISSUE TITLE
the question about photon tracing

### ISSUE THREAD

**Issue by firebrain7** [ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data#6]
Hi Daniel,
 when I update the transfer function,  why does tracePhotons function not be called?
![image](https://user-images.githubusercontent.com/16367644/69495311-986e3f00-0f00-11ea-879f-db99ebb0e6a9.png)

**Comment by ResearchDaniel** [comment]
Have you modified the network such that the linking of transfer function properties have been removed?
This line ensures that the tracePhotons function is called when changing the transfer function:
https://github.com/ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data/blob/2b04718dce5de329a2aa67d952b70afd4aafb691/modules/progressivephotonmapping/processor/progressivephotontracercl.cpp#L149
