### ISSUE TITLE
the workspace problems

### ISSUE THREAD

**Issue by firebrain7** [ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data#7]
after i build with latest version successfully.
the OpenCL seems not work properly.
some examples here:
![image](https://user-images.githubusercontent.com/16367644/70289163-e80d0e80-180e-11ea-913d-8345b733178f.png)
![image](https://user-images.githubusercontent.com/16367644/70289274-36baa880-180f-11ea-88ac-a954fa3b6adc.png)

**Comment by firebrain7** [comment]
it might cuased by the command realted to photon?

**Comment by firebrain7** [comment]
my env:
boost  1.7
python 3.8
vs 2017
inviwo 0.9.11
cuda 10.1 

and cmake console log info:
![image](https://user-images.githubusercontent.com/16367644/70289482-d5470980-180f-11ea-9054-dd258d009f07.png)

**Comment by ResearchDaniel** [comment]
Have you modified any opencl code? It looks for photon in the volumeraycaster.cl code but that should not be the case.

**Comment by firebrain7** [comment]
Hi @ResearchDaniel 
So I try the version without modified. As you can see, the error might due to "photon command" in uniformsamplegenerator2d.cl , however, when i checked the uniformsamplegenerator2d.cl file, there is no "photon command"
Also, do you know in which situations it might fail to find kernel?

![image](https://user-images.githubusercontent.com/16367644/70313979-933eb780-1851-11ea-9295-4023bb15333e.png)
![image](https://user-images.githubusercontent.com/16367644/70314208-ff212000-1851-11ea-9680-f227903de287.png)

**Comment by firebrain7** [comment]
where do you use the command line argument "photon"?

**Comment by firebrain7** [comment]
i also try another workplace ( BaseCL\volumeracster.inv)，result is similar
![image](https://user-images.githubusercontent.com/16367644/70315370-6213b680-1854-11ea-8d3a-771f96932b82.png)

**Comment by firebrain7** [comment]
the things i might not be standard:
I use python 2.7 instead of python 3.x to build, so i remove the inviwo-changelog project(which required 3.x)

**Comment by ResearchDaniel** [comment]
> Also, do you know in which situations it might fail to find kernel?

If a kernel fails to compile it will not find it afterwards.

> where do you use the command line argument "photon"?

It is not used anywhere. I assume that somewhere in your code you have written photon (when compiling a kernel?). I cannot reproduce the error on my machine so I think that you should try it on a fresh checkout and see if the error remains

**Comment by firebrain7** [comment]
in previous build, the inviwo and your module was not modified.
what else might cause it?

**Comment by ResearchDaniel** [comment]
There is probably something wrong when running clBuildProgram. Put a breakpoint there an see which arguments that are passed into the function

**Comment by firebrain7** [comment]
put the breakpoint but without hit?
![image](https://user-images.githubusercontent.com/16367644/70323896-0acc1100-1869-11ea-9ea8-ea025bf6e14f.png)

**Comment by ResearchDaniel** [comment]
Try cl.hpp, the cl::Program class

**Comment by firebrain7** [comment]
sry to bother you. it is not here
![image](https://user-images.githubusercontent.com/16367644/70326236-01de3e00-186f-11ea-8bd0-301c5e74f6dc.png)

**Comment by ResearchDaniel** [comment]
cl.hpp, you are looking in cl.cpp

**Comment by firebrain7** [comment]
i have do set breakpoint where call the function at cl.hpp one hour ago, but still not hit the breakpoint. 
![image](https://user-images.githubusercontent.com/16367644/70331152-d876df80-1879-11ea-8abd-8fbb779e3128.png)

**Comment by ResearchDaniel** [comment]
Are you running in debug or release with debug info? Your breakpoints indicate that they are not active

**Comment by firebrain7** [comment]
thank you a lot Daniel, i still have some problems and I will try to figure it out.
