### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by Donsome** [ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data#9]
- When I followed the tutorial to the fourth step, I encountered an error with CMake. Could you help me take a look?

![4cf3271859c31cbf45c7af29b97ef7a](https://github.com/ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data/assets/45633064/a573c263-6f3d-4aea-b974-ab9ed7f4ed4e)

- the error is here:
> CMake Error at cmake/globalmacros.cmake:469 (source_group):
  source_group ROOT: E:/VolumeRender/code/c/c/c/modules/uniformgridcl/glsl is
  not a prefix of file:
  E:/VolumeRender/code/c/c/c/modules/uniformgridcl/cl/buffermixer.cl
Call Stack (most recent call first):
  E:/VolumeRender/code/c/c/c/modules/uniformgridcl/CMakeLists.txt:53 (ivw_group)

- i dont know how to fix it by modify the CMakeLists.txt

**Comment by ResearchDaniel** [comment]
Hi, for which Inviwo commit are you configuring the project?
Are you using 
https://github.com/inviwo/inviwo/tree/v0.9.11

**Comment by ResearchDaniel** [comment]
As a quick workaround you could try to comment out 
https://github.com/ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data/blob/bb9bd0a79b111a609e4548326d64aede07fd3a5e/modules/uniformgridcl/CMakeLists.txt#L53C38-L53C38
Like so:
`# ivw_group("Shader Files" ${CL_FILES})`

**Comment by Donsome** [comment]
> * i changed  to inviwo 0.9.11  but i got another error when i generate the project .
>   ![image](https://user-images.githubusercontent.com/45633064/253535463-8a5fe03b-7d02-417e-85b4-edce44e87c55.png)

**Comment by Donsome** [comment]
- i changed  to inviwo 0.9.11  but i got another error when i generate the project .
![image](https://github.com/ResearchDaniel/Correlated-Photon-Mapping-for-Interactive-Global-Illumination-of-Time-Varying-Volumetric-Data/assets/45633064/fab5bfc4-b00f-45ec-8bd9-1930070240e2)

**Comment by ResearchDaniel** [comment]
Did you try to comment out the ivw_group before switching version?

**Comment by Donsome** [comment]
no , after i switched to v0.9.11 tag ,  the bug about ivw_group  didn't appear

**Comment by ResearchDaniel** [comment]
Ok, I can see if I can update the code to be compatible with the latest Inviwo version, but it might take some time before I have time to look at it. 

besides the `ivw_group` issue I think that it should mostly be changing some include paths for it to work with the latest inviwo version.

**Comment by ResearchDaniel** [comment]
Fixed in #10
